version: 0.2

env:
  exported-variables:
    - CODEBUILD_BUILD_NUMBER

phases:
  pre_build:
    commands:
      - echo ${AWS_ACCOUNT_ID}
      - echo ${AWS_REGION}
      - echo ${CODEBUILD_BUILD_NUMBER}
      - echo ${CODEBUILD_SRC_DIR}
      - echo ${IMAGE_REPO_NAME}
      
      - apt-get upgrade
      - apt-get update

  build:
    commands:
      - docker build ./grails-multi-app-docker-code-pipeline-example -f ./dockerfile_build_base -t app-build-base:latest

      - docker build ./grails-multi-app-docker-code-pipeline-example/test-app-one -f ./dockerfile_build -t app-one-build  
      - docker build ./grails-multi-app-docker-code-pipeline-example/test-app-one -f ./dockerfile_release -t ${IMAGE_REPO_NAME}:test-app-one-${CODEBUILD_BUILD_NUMBER}
      - docker tag ${IMAGE_REPO_NAME}:test-app-one-${CODEBUILD_BUILD_NUMBER} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:test-app-one-${CODEBUILD_BUILD_NUMBER}

      - app_one_id=$(docker create app-one-build:latest)
      - docker cp $app_one_test_id:/home/TESTS-TestSuites.xml ./app-one-results.xml
      - docker rm -v $app_one_id
      
      - docker build -t ${IMAGE_REPO_NAME}:test-app-two-${CODEBUILD_BUILD_NUMBER} ./grails-multi-app-docker-code-pipeline-example/test-app-two
      - docker tag ${IMAGE_REPO_NAME}:test-app-two-${CODEBUILD_BUILD_NUMBER} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:test-app-two-${CODEBUILD_BUILD_NUMBER}

      - app_two_id=$(docker create ${IMAGE_REPO_NAME}:test-app-two-${CODEBUILD_BUILD_NUMBER})
      - docker cp $app_two_id:/home/TESTS-TestSuites.xml ./app-two-results.xml
      - docker rm -v $app_two_id

  post_build:
    commands:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:test-app-one-${CODEBUILD_BUILD_NUMBER}
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:test-app-two-${CODEBUILD_BUILD_NUMBER}

reports:
  junit-report:
    files:
      - './app-one-results.xml'
      - './app-two-results.xml'
    file-format: 'JUNITXML'

artifacts:    
  files:
    - ./grails-multi-app-docker-code-pipeline-example/cloudformationtemplates/template-private-subnet.yaml
    - ./grails-multi-app-docker-code-pipeline-example/codepipeline/pipeline-stack.yaml